spring.application.name=SampleRestApi

server.port = 9098
server.servlet.context-path=/JpaApp

#Db Connection
spring.datasource.url=jdbc:mysql://localhost:3306/feb26javafsddb
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update